### ISSUE TITLE
Tüm hisseler yok

### ISSUE THREAD

**Issue by emrebuzkiran** [eraykisabacak/Doviz-API#1]
merhabalar. verileri çektiğiniz 'https://uzmanpara.milliyet.com.tr/canli-borsa/' adresinde sadece bist100 hisseleri bulunmakta eğer adresi 'https://uzmanpara.milliyet.com.tr/canli-borsa/bist-TUM-hisseleri/' ile güncellerseniz tüm hisselere api ile erişebiliriz.

**Comment by eraykisabacak** [comment]
Teşekkürler hocam, bende ayrıca bir ekleme yaptım. Bist50 ve Bist30 ekledim.
