### ISSUE TITLE
hisse fiyatları bir önceki hissenin fiyatını gösteriyor 

### ISSUE THREAD

**Issue by emrebuzkiran** [eraykisabacak/Doviz-API#4]
![image](https://github.com/eraykisabacak/Doviz-API/assets/67521326/2db92872-8627-4801-863d-246d70fb5fa6)
![image](https://github.com/eraykisabacak/Doviz-API/assets/67521326/38e9dcf5-f70b-4b67-881a-f08e15de0037)

**Comment by eraykisabacak** [comment]
Teşekkürler
